groups:
- name: PHP
  jobs:
  - create-php-binaries
  - create-buildpack-cflinuxfs3

resources:
- name: binary-builder-source
  type: git
  source:
    uri: https://github.com/bthelen/binary-builder.git
    branch: master
- name: php-buildpack-source
  type: git
  source:
    uri: https://github.com/cloudfoundry/php-buildpack.git
    tag_filter: v4.3.77
- name: php-pipeline-source
  type: git
  source:
    uri: https://github.com/bthelen/php-buildpack-pipeline.git
    branch: cflinuxfs3
- name: oracle-drivers
  type: s3
  source:
    endpoint: ((endpoint))
    bucket: ((s3-bucket-name))
    regexp: oracle-instantclient-12-with-sdk-v(.*).tar.gz
    access_key_id: ((access-key-id))
    secret_access_key: ((secret-access-key))
- name: php-binaries
  type: s3
  source:
    endpoint: ((endpoint))
    bucket: ((s3-bucket-name))
    regexp: php_binaries-v(.*).zip
    access_key_id: ((access-key-id))
    secret_access_key: ((secret-access-key))
- name: php-oracle-buildpack-cflinuxfs3
  type: s3
  source:
    endpoint: ((endpoint))
    bucket: ((s3-bucket-name))
    regexp: php_buildpack-cached-cflinuxfs3-v(.*).zip
    access_key_id: ((access-key-id))
    secret_access_key: ((secret-access-key))

jobs:
- name: create-php-binaries
  serial: true
  plan:
    - get: php-pipeline-source
      trigger: true
    - get: binary-builder-source
      trigger: true
    - get: oracle-drivers
      trigger: false
    - task: create-binaries
      file: php-pipeline-source/tasks/create-binaries.yml
      params:
        PHP_5_VERSION: 5.6.40
        PHP_7_1_VERSION: 7.1.29
        PHP_7_2_VERSION: 7.2.18
        PHP_7_3_VERSION: 7.3.5
    - put: php-binaries
      params:
        file: php-binaries-built/php_binaries-v*.zip
- name: create-buildpack-cflinuxfs3
  serial: true
  plan:
    - get: php-pipeline-source
      trigger: true
      passed: [create-php-binaries]
    - get: php-binaries
      trigger: true
      passed: [create-php-binaries]
    - get: php-buildpack-source
      trigger: true
    - task: create-buildpack-cflinuxfs3
      file: php-pipeline-source/tasks/create-buildpack-cflinuxfs3.yml
      params:
        PHP_5_VERSION: 5.6.40
        PHP_7_1_VERSION: 7.1.29
        PHP_7_2_VERSION: 7.2.18
        PHP_7_3_VERSION: 7.3.5
    - put: php-oracle-buildpack-cflinuxfs3
      params:
        file: php-buildpack-built/php_buildpack-cached-cflinuxfs3-v*.zip
