resources:
- name: binary-builder-source
  type: git
  source:
    uri: https://github.com/cloudfoundry/binary-builder.git
    branch: master
- name: php-buildpack-source
  type: git
  source:
    uri: https://github.com/cloudfoundry/php-buildpack.git
    branch: master
- name: php-pipeline-source
  type: git
  source:
    uri: https://github.com/bthelen/php-buildpack-pipeline.git
    branch: master
- name: oracle-drivers
  type: s3
  source:
    bucket: pa-bthelen-php-buildpack
    regexp: oracle-instantclient-12-with-sdk-v(.*).tar.gz
    access_key_id: ((access-key-id))
    secret_access_key: ((secret-access-key))

jobs:
- name: create-buildpack
  plan:
  - get: php-pipeline-source
    trigger: true
  - get: binary-builder-source
    trigger: true
  - get: php-buildpack-source
    trigger: true
  - get: oracle-drivers
    trigger: false
  - task: create-binaries
    file: php-pipeline-source/tasks/create-binaries.yml
  - task: create-buildpack
    file: php-pipeline-source/tasks/create-buildpack.yml
