platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

inputs:
  - name: php-pipeline-source
  - name: php-binaries-built

run:
  path: php-pipeline-source/tasks/combine-binaries.sh
