platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

inputs:
- name: php-pipeline-source
- name: php-buildpack-source
- name: php-71-binaries
- name: php-73-binaries

outputs:
- name: php-buildpack-built

run:
  path: php-pipeline-source/tasks/create-buildpack-cflinuxfs3.sh
