platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

inputs:
- name: php-pipeline-source
- name: binary-builder-source
- name: php-buildpack-source
- name: oracle-drivers

outputs:
- name: php-binaries-built

run:
  path: php-buildpack-pipeline/tasks/create-binaries.sh
