platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

params:
  PHP_5_VERSION:
  PHP_7_1_VERSION:
  PHP_7_2_VERSION:
  PHP_7_3_VERSION:

inputs:
- name: php-pipeline-source
- name: php-buildpack-source
- name: php-binaries

outputs:
- name: php-buildpack-built

run:
  path: php-pipeline-source/tasks/create-buildpack-cflinuxfs3.sh
