platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

params:
  PHP_5_VERSION: 5.6.37

inputs:
- name: php-pipeline-source
- name: binary-builder-source
- name: oracle-drivers

outputs:
- name: php-binaries-built

run:
  path: php-pipeline-source/tasks/create-binaries.sh
