platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

params:
  PHP_5_VERSION:
  PHP_7_1_VERSION:
  PHP_7_2_VERSION:
  PHP_7_3_VERSION:

inputs:
- name: php-pipeline-source
- name: binary-builder-source
- name: oracle-drivers

outputs:
- name: php-binaries-built

run:
  path: php-pipeline-source/tasks/create-binaries.sh
